### ISSUE TITLE
Select::isOptionDisabled(): Argument #2 ($label) must be of type string, null given

### ISSUE THREAD

**Issue by fonz-lu** [amendozaaguiar/filament-route-statistics#8]
Hi, in my local projects I can access the route statistics, but in production I have the following error :

`Filament\Forms\Components\Select::isOptionDisabled(): Argument #2 ($label) must be of type string, null given, called in /home/..../vendor/filament/forms/src/Components/Select.php on line 187`

I am on Filament v3.2.20

Thanks

**Comment by amendozaaguiar** [comment]
I reviewed your report and found that the issue is due to your database in the 'route_statistics' table, specifically in the 'route' field, where there are records with NULL values, causing the mentioned error. I will look for a solution for this type of case. For now, you can validate your information. 🧐

**Comment by fonz-lu** [comment]
When I search in the database for records where 'route' is null, I cannot find any. team_id is always null and user_id sometimes. 

I did truncate the table, but the error is still present

**Comment by amendozaaguiar** [comment]
The package has been fully updated, check latest version.

**Comment by fonz-lu** [comment]
Hi @amendozaaguiar,

the bug has been resolved.

Thank you
